language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - IDENTITY_SERVICE_HOST=null
  - CORE_SERVICE_HOST=null
  - GEMFURY_USER=neoncity
  - AUTH0_CLIENT_ID=null
  - AUTH0_DOMAIN=null
  - AUTH0_CALLBACK_URI=null
  - FILESTACK_KEY=null
  - FACEBOOK_APP_ID=null
  # GEMFURY_API_KEY=???
  - secure: "XlmjrqUgKEAOVN8xnOx/VDjAT5XI6OoSA1doQdgxu0TpG7a1QHV1VeV7frwzltlEmyl9cuzVBK6e4gwBJfO9qWqtOHXznj7vdobV+TVBQzLIN+MyS5d1lIbN/P+7vRMXwzJ99Z5LAtBnzL1zaxS+U2BZxPMyM2t+EUYBVIzEZslQsB8pD8+z44hY2+TZRuDp6iDE7ZyoE/f0hCPa9adFdPz/SpXTAu9eNR+QilMScmjX35Xa4dVnI2GM+mWtVtUO1ysNQG8i1IIGW+AQcX5NAh03JU3LZZjmr8RA+sK1eQsXnONUYtAv1QiIpEnW37UFggiYXnJQd7wMKn5RQ4cFNY8opGVzVGLQp3GA/EN3Y4q+hqRJLHeaa7P66jSv+u7yw70vSe/JD2vh/CZyw/MyBG6+FXwLvoL3LjPQxj6OyRz1gkUImZHcLhShAN4zEHuioZOyq5h0oAZV59yZT6u76XfE/PcoSbWQ6C7oliu/t7MALsmvvhX5k4MbxvUziYoXgtlLSiwroUB6S8LKPaBDSsOr1mN99ZAijX2RsBYLCIDZxS9ndQFX6ngl5Ln8Uengv5sICawJ7d9B0Z4zIghlpm33r/5jJJwm6GFE/8Zz1gxLrf6/+6alkz2SBfhsAiCf7UhB3vPMOUOowqJ/fn6cCGehif6ANNomv13he5vTqz4="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/togemfury --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
- provider: heroku
  skip_cleanup: true
  app: causefe-staging-neoncity
  api_key:
    secure: "Q8lIh8g/Bu3Vl0ED2MNVD1oUsrRVlwettbq/M48evpusK0lWP3uY89DoY0hN1G+uQnt/70uw8jL0ulo0Clp342UHjqSa82YzvIWDu3s3gRL17KiMCsBicrSYqoZf+UKvz4p8K8UZQFP6b8tVEFO/tDpiVilBIJ1oq1piKko9wvVCCkAppm1HZBCrvNF91Q0VCe2Hw6P0tODnWjEpWWHK1NyZUuNF9IkplzZkaiovbTnp0ODbJG5I1JqWWNTpoJhlGHNufsgToR3piiU8uR+eM02LwKFPtlg7ds7VTrrS/FM9YTX6T5G+Rp72NnVSzGbc/3dz3FXyzb58XFAlEffS88dd1IdExsHFIf+78zSx7C5jDtN501rV9z54L3BtwqIII+B8AXUniIsCyjNVJFoA8j+fp6n6khDCjKMX2dek9MJ01dR4d0wCmIB8+0prq/zrCGWfZjhLg3TeDgMhxASmRhwSZqAy/BP4wVa0RLKcRkE4xry0tVqhytMN6/v6jHswToA3gxbVdN7lxCnJGp39/hBhHOgFwvKBnLQbUIN8dKaB9aIlf666W0SmQlavA68Re/17B5dOvO71BKPull7kGwfHEU9WVqi39ZKmipuYyjkTXZ1xhE4anbpFqVOrk/g/qm+xVlItV6i6mRMge3sZvGdn7l9qjsjdpcazMeNaOXU="
